// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: echo.proto

// example 是 grpcapi 的最小接入面活文档（DESIGN.md §3：README 接入清单 ≤ 6 步，
// example 不得超出该清单引入额外必需步骤）。本文件演示契约层：
// google.api.http 路由 + grpcapi.v1 authz 注解（策略唯一声明源）。

package echov1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/lynx-go/grpcapi/genproto/grpcapi/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShoutRequest) Reset() {
	*x = ShoutRequest{}
	mi := &file_echo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShoutRequest) ProtoMessage() {}

func (x *ShoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_echo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShoutRequest.ProtoReflect.Descriptor instead.
func (*ShoutRequest) Descriptor() ([]byte, []int) {
	return file_echo_proto_rawDescGZIP(), []int{0}
}

func (x *ShoutRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ShoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Length        int32                  `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShoutResponse) Reset() {
	*x = ShoutResponse{}
	mi := &file_echo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShoutResponse) ProtoMessage() {}

func (x *ShoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_echo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShoutResponse.ProtoReflect.Descriptor instead.
func (*ShoutResponse) Descriptor() ([]byte, []int) {
	return file_echo_proto_rawDescGZIP(), []int{1}
}

func (x *ShoutResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ShoutResponse) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type HearRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        string                 `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HearRequest) Reset() {
	*x = HearRequest{}
	mi := &file_echo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HearRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HearRequest) ProtoMessage() {}

func (x *HearRequest) ProtoReflect() protoreflect.Message {
	mi := &file_echo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HearRequest.ProtoReflect.Descriptor instead.
func (*HearRequest) Descriptor() ([]byte, []int) {
	return file_echo_proto_rawDescGZIP(), []int{2}
}

func (x *HearRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type HearResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lines         []string               `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HearResponse) Reset() {
	*x = HearResponse{}
	mi := &file_echo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HearResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HearResponse) ProtoMessage() {}

func (x *HearResponse) ProtoReflect() protoreflect.Message {
	mi := &file_echo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HearResponse.ProtoReflect.Descriptor instead.
func (*HearResponse) Descriptor() ([]byte, []int) {
	return file_echo_proto_rawDescGZIP(), []int{3}
}

func (x *HearResponse) GetLines() []string {
	if x != nil {
		return x.Lines
	}
	return nil
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_echo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_echo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_echo_proto_rawDescGZIP(), []int{4}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pong          string                 `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_echo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_echo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_echo_proto_rawDescGZIP(), []int{5}
}

func (x *PingResponse) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

var File_echo_proto protoreflect.FileDescriptor

const file_echo_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"echo.proto\x12\x0fexample.echo.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x16grpcapi/v1/authz.proto\",\n" +
	"\fShoutRequest\x12\x1c\n" +
	"\x04text\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x01R\x04text\";\n" +
	"\rShoutResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x05R\x06length\"%\n" +
	"\vHearRequest\x12\x16\n" +
	"\x06filter\x18\x01 \x01(\tR\x06filter\"$\n" +
	"\fHearResponse\x12\x14\n" +
	"\x05lines\x18\x01 \x03(\tR\x05lines\"\r\n" +
	"\vPingRequest\"\"\n" +
	"\fPingResponse\x12\x12\n" +
	"\x04pong\x18\x01 \x01(\tR\x04pong2\xc3\x02\n" +
	"\vEchoService\x12s\n" +
	"\x05Shout\x12\x1d.example.echo.v1.ShoutRequest\x1a\x1e.example.echo.v1.ShoutResponse\"+\xea\xc4\x19\x0e\b\x03\"\n" +
	"\n" +
	"\x06echoes\x10\x02\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/echo:shout\x12U\n" +
	"\x04Hear\x12\x1c.example.echo.v1.HearRequest\x1a\x1d.example.echo.v1.HearResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/v1/echo\x12`\n" +
	"\x04Ping\x12\x1c.example.echo.v1.PingRequest\x1a\x1d.example.echo.v1.PingResponse\"\x1b\xea\xc4\x19\x02\b\x01\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/echo:ping\x1a\x06\xf2\xc4\x19\x02\b\x02B3Z1github.com/lynx-go/grpcapi/example/echo/v1;echov1b\x06proto3"

var (
	file_echo_proto_rawDescOnce sync.Once
	file_echo_proto_rawDescData []byte
)

func file_echo_proto_rawDescGZIP() []byte {
	file_echo_proto_rawDescOnce.Do(func() {
		file_echo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_echo_proto_rawDesc), len(file_echo_proto_rawDesc)))
	})
	return file_echo_proto_rawDescData
}

var file_echo_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_echo_proto_goTypes = []any{
	(*ShoutRequest)(nil),  // 0: example.echo.v1.ShoutRequest
	(*ShoutResponse)(nil), // 1: example.echo.v1.ShoutResponse
	(*HearRequest)(nil),   // 2: example.echo.v1.HearRequest
	(*HearResponse)(nil),  // 3: example.echo.v1.HearResponse
	(*PingRequest)(nil),   // 4: example.echo.v1.PingRequest
	(*PingResponse)(nil),  // 5: example.echo.v1.PingResponse
}
var file_echo_proto_depIdxs = []int32{
	0, // 0: example.echo.v1.EchoService.Shout:input_type -> example.echo.v1.ShoutRequest
	2, // 1: example.echo.v1.EchoService.Hear:input_type -> example.echo.v1.HearRequest
	4, // 2: example.echo.v1.EchoService.Ping:input_type -> example.echo.v1.PingRequest
	1, // 3: example.echo.v1.EchoService.Shout:output_type -> example.echo.v1.ShoutResponse
	3, // 4: example.echo.v1.EchoService.Hear:output_type -> example.echo.v1.HearResponse
	5, // 5: example.echo.v1.EchoService.Ping:output_type -> example.echo.v1.PingResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_echo_proto_init() }
func file_echo_proto_init() {
	if File_echo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_echo_proto_rawDesc), len(file_echo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_echo_proto_goTypes,
		DependencyIndexes: file_echo_proto_depIdxs,
		MessageInfos:      file_echo_proto_msgTypes,
	}.Build()
	File_echo_proto = out.File
	file_echo_proto_goTypes = nil
	file_echo_proto_depIdxs = nil
}
