// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: grpcapi/v1/authz.proto

// Package grpcapi.v1 定义 authz 策略注解扩展：proto 是策略唯一声明源，
// 运行时由 github.com/lynx-go/grpcapi/authz.Build 收集为 PolicySet 并做
// fail-closed 断言（缺注解、词表外的资源、语义违例均启动失败）。
//
// 字段号 52301/52302 刻意避开 torchwood 历史号段（52001/52002）：
// 扩展字段号在 wire 层没有 package 命名空间，同号不同型的两套扩展
// 并存于一个二进制时 GetExtension 会静默跳过，注解丢失无任何报错。

package grpcapiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AccessLevel 是凭证族维度的访问档位（值域稳定，由库持有）。
type AccessLevel int32

const (
	// 未声明。收集器视缺失注解/缺省值为启动错误（fail-closed）。
	AccessLevel_ACCESS_LEVEL_UNSPECIFIED AccessLevel = 0
	// 无凭证可调用；携带无效凭证时的处理由项目 auth 拦截器决定。
	AccessLevel_ACCESS_LEVEL_PUBLIC AccessLevel = 1
	// 终端用户凭证（JWT/session）。
	AccessLevel_ACCESS_LEVEL_END_USER AccessLevel = 2
	// 服务面：admin 会话与 scoped API key（api_key_scope 把关）。
	AccessLevel_ACCESS_LEVEL_SERVER AccessLevel = 3
	// 角色权限面（permissions 把关；API key 凭证一律拒绝）。
	AccessLevel_ACCESS_LEVEL_PERMISSION AccessLevel = 4
	// 保留：v1 禁用，收集器对使用该档位的方法启动报错。
	AccessLevel_ACCESS_LEVEL_SYSTEM AccessLevel = 5
)

// Enum value maps for AccessLevel.
var (
	AccessLevel_name = map[int32]string{
		0: "ACCESS_LEVEL_UNSPECIFIED",
		1: "ACCESS_LEVEL_PUBLIC",
		2: "ACCESS_LEVEL_END_USER",
		3: "ACCESS_LEVEL_SERVER",
		4: "ACCESS_LEVEL_PERMISSION",
		5: "ACCESS_LEVEL_SYSTEM",
	}
	AccessLevel_value = map[string]int32{
		"ACCESS_LEVEL_UNSPECIFIED": 0,
		"ACCESS_LEVEL_PUBLIC":      1,
		"ACCESS_LEVEL_END_USER":    2,
		"ACCESS_LEVEL_SERVER":      3,
		"ACCESS_LEVEL_PERMISSION":  4,
		"ACCESS_LEVEL_SYSTEM":      5,
	}
)

func (x AccessLevel) Enum() *AccessLevel {
	p := new(AccessLevel)
	*p = x
	return p
}

func (x AccessLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_grpcapi_v1_authz_proto_enumTypes[0].Descriptor()
}

func (AccessLevel) Type() protoreflect.EnumType {
	return &file_grpcapi_v1_authz_proto_enumTypes[0]
}

func (x AccessLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessLevel.Descriptor instead.
func (AccessLevel) EnumDescriptor() ([]byte, []int) {
	return file_grpcapi_v1_authz_proto_rawDescGZIP(), []int{0}
}

// ScopeOp 是 API key scope 的权限方向（值域稳定，由库持有）。
type ScopeOp int32

const (
	ScopeOp_SCOPE_OP_UNSPECIFIED ScopeOp = 0
	ScopeOp_SCOPE_OP_READ        ScopeOp = 1
	ScopeOp_SCOPE_OP_WRITE       ScopeOp = 2
	ScopeOp_SCOPE_OP_ADMIN       ScopeOp = 3
)

// Enum value maps for ScopeOp.
var (
	ScopeOp_name = map[int32]string{
		0: "SCOPE_OP_UNSPECIFIED",
		1: "SCOPE_OP_READ",
		2: "SCOPE_OP_WRITE",
		3: "SCOPE_OP_ADMIN",
	}
	ScopeOp_value = map[string]int32{
		"SCOPE_OP_UNSPECIFIED": 0,
		"SCOPE_OP_READ":        1,
		"SCOPE_OP_WRITE":       2,
		"SCOPE_OP_ADMIN":       3,
	}
)

func (x ScopeOp) Enum() *ScopeOp {
	p := new(ScopeOp)
	*p = x
	return p
}

func (x ScopeOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScopeOp) Descriptor() protoreflect.EnumDescriptor {
	return file_grpcapi_v1_authz_proto_enumTypes[1].Descriptor()
}

func (ScopeOp) Type() protoreflect.EnumType {
	return &file_grpcapi_v1_authz_proto_enumTypes[1]
}

func (x ScopeOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScopeOp.Descriptor instead.
func (ScopeOp) EnumDescriptor() ([]byte, []int) {
	return file_grpcapi_v1_authz_proto_rawDescGZIP(), []int{1}
}

// APIKeyScope 声明 SERVER 面方法对 API key 凭证开放的 scope 门。
// resource 的词表主权在项目：值为项目注册的 Vocabulary 中的字符串
// （建议以项目 domain 持久化形态为基准），收集期做 fail-closed 校验。
type APIKeyScope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Op            ScopeOp                `protobuf:"varint,2,opt,name=op,proto3,enum=grpcapi.v1.ScopeOp" json:"op,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIKeyScope) Reset() {
	*x = APIKeyScope{}
	mi := &file_grpcapi_v1_authz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIKeyScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKeyScope) ProtoMessage() {}

func (x *APIKeyScope) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapi_v1_authz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKeyScope.ProtoReflect.Descriptor instead.
func (*APIKeyScope) Descriptor() ([]byte, []int) {
	return file_grpcapi_v1_authz_proto_rawDescGZIP(), []int{0}
}

func (x *APIKeyScope) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *APIKeyScope) GetOp() ScopeOp {
	if x != nil {
		return x.Op
	}
	return ScopeOp_SCOPE_OP_UNSPECIFIED
}

// MethodAuth 是方法级 authz 策略；缺省回落 service_auth.default_access。
type MethodAuth struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Access AccessLevel            `protobuf:"varint,1,opt,name=access,proto3,enum=grpcapi.v1.AccessLevel" json:"access,omitempty"`
	// PERMISSION 面的角色权限门（值域主权在项目）。
	Permissions []string `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	// SERVER 面的 admin 会话角色门（值域主权在项目）。
	AdminRoles []string `protobuf:"bytes,3,rep,name=admin_roles,json=adminRoles,proto3" json:"admin_roles,omitempty"`
	// SERVER 面的 API key scope 门；缺省 = 该方法不对 key 开放。
	ApiKeyScope   *APIKeyScope `protobuf:"bytes,4,opt,name=api_key_scope,json=apiKeyScope,proto3" json:"api_key_scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MethodAuth) Reset() {
	*x = MethodAuth{}
	mi := &file_grpcapi_v1_authz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MethodAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodAuth) ProtoMessage() {}

func (x *MethodAuth) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapi_v1_authz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodAuth.ProtoReflect.Descriptor instead.
func (*MethodAuth) Descriptor() ([]byte, []int) {
	return file_grpcapi_v1_authz_proto_rawDescGZIP(), []int{1}
}

func (x *MethodAuth) GetAccess() AccessLevel {
	if x != nil {
		return x.Access
	}
	return AccessLevel_ACCESS_LEVEL_UNSPECIFIED
}

func (x *MethodAuth) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *MethodAuth) GetAdminRoles() []string {
	if x != nil {
		return x.AdminRoles
	}
	return nil
}

func (x *MethodAuth) GetApiKeyScope() *APIKeyScope {
	if x != nil {
		return x.ApiKeyScope
	}
	return nil
}

// ServiceAuth 是服务级缺省档位。
type ServiceAuth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DefaultAccess AccessLevel            `protobuf:"varint,1,opt,name=default_access,json=defaultAccess,proto3,enum=grpcapi.v1.AccessLevel" json:"default_access,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceAuth) Reset() {
	*x = ServiceAuth{}
	mi := &file_grpcapi_v1_authz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceAuth) ProtoMessage() {}

func (x *ServiceAuth) ProtoReflect() protoreflect.Message {
	mi := &file_grpcapi_v1_authz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceAuth.ProtoReflect.Descriptor instead.
func (*ServiceAuth) Descriptor() ([]byte, []int) {
	return file_grpcapi_v1_authz_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceAuth) GetDefaultAccess() AccessLevel {
	if x != nil {
		return x.DefaultAccess
	}
	return AccessLevel_ACCESS_LEVEL_UNSPECIFIED
}

var file_grpcapi_v1_authz_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*MethodAuth)(nil),
		Field:         52301,
		Name:          "grpcapi.v1.method_auth",
		Tag:           "bytes,52301,opt,name=method_auth",
		Filename:      "grpcapi/v1/authz.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*ServiceAuth)(nil),
		Field:         52302,
		Name:          "grpcapi.v1.service_auth",
		Tag:           "bytes,52302,opt,name=service_auth",
		Filename:      "grpcapi/v1/authz.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional grpcapi.v1.MethodAuth method_auth = 52301;
	E_MethodAuth = &file_grpcapi_v1_authz_proto_extTypes[0]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional grpcapi.v1.ServiceAuth service_auth = 52302;
	E_ServiceAuth = &file_grpcapi_v1_authz_proto_extTypes[1]
)

var File_grpcapi_v1_authz_proto protoreflect.FileDescriptor

const file_grpcapi_v1_authz_proto_rawDesc = "" +
	"\n" +
	"\x16grpcapi/v1/authz.proto\x12\n" +
	"grpcapi.v1\x1a google/protobuf/descriptor.proto\"N\n" +
	"\vAPIKeyScope\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12#\n" +
	"\x02op\x18\x02 \x01(\x0e2\x13.grpcapi.v1.ScopeOpR\x02op\"\xbd\x01\n" +
	"\n" +
	"MethodAuth\x12/\n" +
	"\x06access\x18\x01 \x01(\x0e2\x17.grpcapi.v1.AccessLevelR\x06access\x12 \n" +
	"\vpermissions\x18\x02 \x03(\tR\vpermissions\x12\x1f\n" +
	"\vadmin_roles\x18\x03 \x03(\tR\n" +
	"adminRoles\x12;\n" +
	"\rapi_key_scope\x18\x04 \x01(\v2\x17.grpcapi.v1.APIKeyScopeR\vapiKeyScope\"M\n" +
	"\vServiceAuth\x12>\n" +
	"\x0edefault_access\x18\x01 \x01(\x0e2\x17.grpcapi.v1.AccessLevelR\rdefaultAccess*\xae\x01\n" +
	"\vAccessLevel\x12\x1c\n" +
	"\x18ACCESS_LEVEL_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ACCESS_LEVEL_PUBLIC\x10\x01\x12\x19\n" +
	"\x15ACCESS_LEVEL_END_USER\x10\x02\x12\x17\n" +
	"\x13ACCESS_LEVEL_SERVER\x10\x03\x12\x1b\n" +
	"\x17ACCESS_LEVEL_PERMISSION\x10\x04\x12\x17\n" +
	"\x13ACCESS_LEVEL_SYSTEM\x10\x05*^\n" +
	"\aScopeOp\x12\x18\n" +
	"\x14SCOPE_OP_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSCOPE_OP_READ\x10\x01\x12\x12\n" +
	"\x0eSCOPE_OP_WRITE\x10\x02\x12\x12\n" +
	"\x0eSCOPE_OP_ADMIN\x10\x03:Y\n" +
	"\vmethod_auth\x12\x1e.google.protobuf.MethodOptions\x18͘\x03 \x01(\v2\x16.grpcapi.v1.MethodAuthR\n" +
	"methodAuth:]\n" +
	"\fservice_auth\x12\x1f.google.protobuf.ServiceOptions\x18Θ\x03 \x01(\v2\x17.grpcapi.v1.ServiceAuthR\vserviceAuthB:Z8github.com/lynx-go/grpcapi/genproto/grpcapi/v1;grpcapiv1b\x06proto3"

var (
	file_grpcapi_v1_authz_proto_rawDescOnce sync.Once
	file_grpcapi_v1_authz_proto_rawDescData []byte
)

func file_grpcapi_v1_authz_proto_rawDescGZIP() []byte {
	file_grpcapi_v1_authz_proto_rawDescOnce.Do(func() {
		file_grpcapi_v1_authz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpcapi_v1_authz_proto_rawDesc), len(file_grpcapi_v1_authz_proto_rawDesc)))
	})
	return file_grpcapi_v1_authz_proto_rawDescData
}

var file_grpcapi_v1_authz_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_grpcapi_v1_authz_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grpcapi_v1_authz_proto_goTypes = []any{
	(AccessLevel)(0),                    // 0: grpcapi.v1.AccessLevel
	(ScopeOp)(0),                        // 1: grpcapi.v1.ScopeOp
	(*APIKeyScope)(nil),                 // 2: grpcapi.v1.APIKeyScope
	(*MethodAuth)(nil),                  // 3: grpcapi.v1.MethodAuth
	(*ServiceAuth)(nil),                 // 4: grpcapi.v1.ServiceAuth
	(*descriptorpb.MethodOptions)(nil),  // 5: google.protobuf.MethodOptions
	(*descriptorpb.ServiceOptions)(nil), // 6: google.protobuf.ServiceOptions
}
var file_grpcapi_v1_authz_proto_depIdxs = []int32{
	1, // 0: grpcapi.v1.APIKeyScope.op:type_name -> grpcapi.v1.ScopeOp
	0, // 1: grpcapi.v1.MethodAuth.access:type_name -> grpcapi.v1.AccessLevel
	2, // 2: grpcapi.v1.MethodAuth.api_key_scope:type_name -> grpcapi.v1.APIKeyScope
	0, // 3: grpcapi.v1.ServiceAuth.default_access:type_name -> grpcapi.v1.AccessLevel
	5, // 4: grpcapi.v1.method_auth:extendee -> google.protobuf.MethodOptions
	6, // 5: grpcapi.v1.service_auth:extendee -> google.protobuf.ServiceOptions
	3, // 6: grpcapi.v1.method_auth:type_name -> grpcapi.v1.MethodAuth
	4, // 7: grpcapi.v1.service_auth:type_name -> grpcapi.v1.ServiceAuth
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	6, // [6:8] is the sub-list for extension type_name
	4, // [4:6] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_grpcapi_v1_authz_proto_init() }
func file_grpcapi_v1_authz_proto_init() {
	if File_grpcapi_v1_authz_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpcapi_v1_authz_proto_rawDesc), len(file_grpcapi_v1_authz_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_grpcapi_v1_authz_proto_goTypes,
		DependencyIndexes: file_grpcapi_v1_authz_proto_depIdxs,
		EnumInfos:         file_grpcapi_v1_authz_proto_enumTypes,
		MessageInfos:      file_grpcapi_v1_authz_proto_msgTypes,
		ExtensionInfos:    file_grpcapi_v1_authz_proto_extTypes,
	}.Build()
	File_grpcapi_v1_authz_proto = out.File
	file_grpcapi_v1_authz_proto_goTypes = nil
	file_grpcapi_v1_authz_proto_depIdxs = nil
}
