// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: fixture.proto

// fixture 是 authz.Build 的合法策略夹具：以真实 FileDescriptor 驱动收集器，
// 覆盖 method_auth 优先、service_auth 回落、SERVER+scope（read/write/admin
// 三方向）、PERMISSION+permissions、PUBLIC、流式方法（配 AllowStreaming）与
// RequestFields 排序投影。故意违例的场景见 violations.proto，无 scope 声明面
// 见 plain.proto。

package testdata

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FixturePriorityService_GetItem_FullMethodName   = "/grpcapi.authz.testdata.v1.FixturePriorityService/GetItem"
	FixturePriorityService_ListItems_FullMethodName = "/grpcapi.authz.testdata.v1.FixturePriorityService/ListItems"
)

// FixturePriorityServiceClient is the client API for FixturePriorityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FixturePriorityService 验证优先级语义：service_auth 提供缺省档，
// method_auth 逐方法覆盖。
type FixturePriorityServiceClient interface {
	// GetItem 用 method_auth 覆盖服务缺省档（END_USER → SERVER）。
	GetItem(ctx context.Context, in *GetItemRequest, opts ...grpc.CallOption) (*GetItemResponse, error)
	// ListItems 不带 method_auth，回落 service_auth.default_access（END_USER；
	// permissions 保持为空——归一化是项目策略，不进库）。
	ListItems(ctx context.Context, in *ListItemsRequest, opts ...grpc.CallOption) (*ListItemsResponse, error)
}

type fixturePriorityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFixturePriorityServiceClient(cc grpc.ClientConnInterface) FixturePriorityServiceClient {
	return &fixturePriorityServiceClient{cc}
}

func (c *fixturePriorityServiceClient) GetItem(ctx context.Context, in *GetItemRequest, opts ...grpc.CallOption) (*GetItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetItemResponse)
	err := c.cc.Invoke(ctx, FixturePriorityService_GetItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fixturePriorityServiceClient) ListItems(ctx context.Context, in *ListItemsRequest, opts ...grpc.CallOption) (*ListItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListItemsResponse)
	err := c.cc.Invoke(ctx, FixturePriorityService_ListItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FixturePriorityServiceServer is the server API for FixturePriorityService service.
// All implementations must embed UnimplementedFixturePriorityServiceServer
// for forward compatibility.
//
// FixturePriorityService 验证优先级语义：service_auth 提供缺省档，
// method_auth 逐方法覆盖。
type FixturePriorityServiceServer interface {
	// GetItem 用 method_auth 覆盖服务缺省档（END_USER → SERVER）。
	GetItem(context.Context, *GetItemRequest) (*GetItemResponse, error)
	// ListItems 不带 method_auth，回落 service_auth.default_access（END_USER；
	// permissions 保持为空——归一化是项目策略，不进库）。
	ListItems(context.Context, *ListItemsRequest) (*ListItemsResponse, error)
	mustEmbedUnimplementedFixturePriorityServiceServer()
}

// UnimplementedFixturePriorityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFixturePriorityServiceServer struct{}

func (UnimplementedFixturePriorityServiceServer) GetItem(context.Context, *GetItemRequest) (*GetItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetItem not implemented")
}
func (UnimplementedFixturePriorityServiceServer) ListItems(context.Context, *ListItemsRequest) (*ListItemsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListItems not implemented")
}
func (UnimplementedFixturePriorityServiceServer) mustEmbedUnimplementedFixturePriorityServiceServer() {
}
func (UnimplementedFixturePriorityServiceServer) testEmbeddedByValue() {}

// UnsafeFixturePriorityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FixturePriorityServiceServer will
// result in compilation errors.
type UnsafeFixturePriorityServiceServer interface {
	mustEmbedUnimplementedFixturePriorityServiceServer()
}

func RegisterFixturePriorityServiceServer(s grpc.ServiceRegistrar, srv FixturePriorityServiceServer) {
	// If the following call panics, it indicates UnimplementedFixturePriorityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FixturePriorityService_ServiceDesc, srv)
}

func _FixturePriorityService_GetItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FixturePriorityServiceServer).GetItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FixturePriorityService_GetItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FixturePriorityServiceServer).GetItem(ctx, req.(*GetItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FixturePriorityService_ListItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FixturePriorityServiceServer).ListItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FixturePriorityService_ListItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FixturePriorityServiceServer).ListItems(ctx, req.(*ListItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FixturePriorityService_ServiceDesc is the grpc.ServiceDesc for FixturePriorityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FixturePriorityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcapi.authz.testdata.v1.FixturePriorityService",
	HandlerType: (*FixturePriorityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetItem",
			Handler:    _FixturePriorityService_GetItem_Handler,
		},
		{
			MethodName: "ListItems",
			Handler:    _FixturePriorityService_ListItems_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fixture.proto",
}

const (
	FixtureServerService_CreateItem_FullMethodName = "/grpcapi.authz.testdata.v1.FixtureServerService/CreateItem"
	FixtureServerService_DeleteItem_FullMethodName = "/grpcapi.authz.testdata.v1.FixtureServerService/DeleteItem"
)

// FixtureServerServiceClient is the client API for FixtureServerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FixtureServerService 全方法显式声明，覆盖 SERVER 面 scope 的
// write / admin 方向与 admin_roles 透传。
type FixtureServerServiceClient interface {
	CreateItem(ctx context.Context, in *CreateItemRequest, opts ...grpc.CallOption) (*CreateItemResponse, error)
	DeleteItem(ctx context.Context, in *DeleteItemRequest, opts ...grpc.CallOption) (*DeleteItemResponse, error)
}

type fixtureServerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFixtureServerServiceClient(cc grpc.ClientConnInterface) FixtureServerServiceClient {
	return &fixtureServerServiceClient{cc}
}

func (c *fixtureServerServiceClient) CreateItem(ctx context.Context, in *CreateItemRequest, opts ...grpc.CallOption) (*CreateItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateItemResponse)
	err := c.cc.Invoke(ctx, FixtureServerService_CreateItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fixtureServerServiceClient) DeleteItem(ctx context.Context, in *DeleteItemRequest, opts ...grpc.CallOption) (*DeleteItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteItemResponse)
	err := c.cc.Invoke(ctx, FixtureServerService_DeleteItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FixtureServerServiceServer is the server API for FixtureServerService service.
// All implementations must embed UnimplementedFixtureServerServiceServer
// for forward compatibility.
//
// FixtureServerService 全方法显式声明，覆盖 SERVER 面 scope 的
// write / admin 方向与 admin_roles 透传。
type FixtureServerServiceServer interface {
	CreateItem(context.Context, *CreateItemRequest) (*CreateItemResponse, error)
	DeleteItem(context.Context, *DeleteItemRequest) (*DeleteItemResponse, error)
	mustEmbedUnimplementedFixtureServerServiceServer()
}

// UnimplementedFixtureServerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFixtureServerServiceServer struct{}

func (UnimplementedFixtureServerServiceServer) CreateItem(context.Context, *CreateItemRequest) (*CreateItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateItem not implemented")
}
func (UnimplementedFixtureServerServiceServer) DeleteItem(context.Context, *DeleteItemRequest) (*DeleteItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteItem not implemented")
}
func (UnimplementedFixtureServerServiceServer) mustEmbedUnimplementedFixtureServerServiceServer() {}
func (UnimplementedFixtureServerServiceServer) testEmbeddedByValue()                              {}

// UnsafeFixtureServerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FixtureServerServiceServer will
// result in compilation errors.
type UnsafeFixtureServerServiceServer interface {
	mustEmbedUnimplementedFixtureServerServiceServer()
}

func RegisterFixtureServerServiceServer(s grpc.ServiceRegistrar, srv FixtureServerServiceServer) {
	// If the following call panics, it indicates UnimplementedFixtureServerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FixtureServerService_ServiceDesc, srv)
}

func _FixtureServerService_CreateItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FixtureServerServiceServer).CreateItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FixtureServerService_CreateItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FixtureServerServiceServer).CreateItem(ctx, req.(*CreateItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FixtureServerService_DeleteItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FixtureServerServiceServer).DeleteItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FixtureServerService_DeleteItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FixtureServerServiceServer).DeleteItem(ctx, req.(*DeleteItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FixtureServerService_ServiceDesc is the grpc.ServiceDesc for FixtureServerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FixtureServerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcapi.authz.testdata.v1.FixtureServerService",
	HandlerType: (*FixtureServerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateItem",
			Handler:    _FixtureServerService_CreateItem_Handler,
		},
		{
			MethodName: "DeleteItem",
			Handler:    _FixtureServerService_DeleteItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fixture.proto",
}

const (
	FixturePermissionService_PurgeItems_FullMethodName = "/grpcapi.authz.testdata.v1.FixturePermissionService/PurgeItems"
)

// FixturePermissionServiceClient is the client API for FixturePermissionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FixturePermissionService 覆盖 PERMISSION 面（permissions 原样透传）。
type FixturePermissionServiceClient interface {
	PurgeItems(ctx context.Context, in *PurgeItemsRequest, opts ...grpc.CallOption) (*PurgeItemsResponse, error)
}

type fixturePermissionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFixturePermissionServiceClient(cc grpc.ClientConnInterface) FixturePermissionServiceClient {
	return &fixturePermissionServiceClient{cc}
}

func (c *fixturePermissionServiceClient) PurgeItems(ctx context.Context, in *PurgeItemsRequest, opts ...grpc.CallOption) (*PurgeItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PurgeItemsResponse)
	err := c.cc.Invoke(ctx, FixturePermissionService_PurgeItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FixturePermissionServiceServer is the server API for FixturePermissionService service.
// All implementations must embed UnimplementedFixturePermissionServiceServer
// for forward compatibility.
//
// FixturePermissionService 覆盖 PERMISSION 面（permissions 原样透传）。
type FixturePermissionServiceServer interface {
	PurgeItems(context.Context, *PurgeItemsRequest) (*PurgeItemsResponse, error)
	mustEmbedUnimplementedFixturePermissionServiceServer()
}

// UnimplementedFixturePermissionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFixturePermissionServiceServer struct{}

func (UnimplementedFixturePermissionServiceServer) PurgeItems(context.Context, *PurgeItemsRequest) (*PurgeItemsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PurgeItems not implemented")
}
func (UnimplementedFixturePermissionServiceServer) mustEmbedUnimplementedFixturePermissionServiceServer() {
}
func (UnimplementedFixturePermissionServiceServer) testEmbeddedByValue() {}

// UnsafeFixturePermissionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FixturePermissionServiceServer will
// result in compilation errors.
type UnsafeFixturePermissionServiceServer interface {
	mustEmbedUnimplementedFixturePermissionServiceServer()
}

func RegisterFixturePermissionServiceServer(s grpc.ServiceRegistrar, srv FixturePermissionServiceServer) {
	// If the following call panics, it indicates UnimplementedFixturePermissionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FixturePermissionService_ServiceDesc, srv)
}

func _FixturePermissionService_PurgeItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurgeItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FixturePermissionServiceServer).PurgeItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FixturePermissionService_PurgeItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FixturePermissionServiceServer).PurgeItems(ctx, req.(*PurgeItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FixturePermissionService_ServiceDesc is the grpc.ServiceDesc for FixturePermissionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FixturePermissionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcapi.authz.testdata.v1.FixturePermissionService",
	HandlerType: (*FixturePermissionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PurgeItems",
			Handler:    _FixturePermissionService_PurgeItems_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fixture.proto",
}

const (
	FixturePublicService_Ping_FullMethodName = "/grpcapi.authz.testdata.v1.FixturePublicService/Ping"
)

// FixturePublicServiceClient is the client API for FixturePublicService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FixturePublicService 覆盖 PUBLIC 面。
type FixturePublicServiceClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type fixturePublicServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFixturePublicServiceClient(cc grpc.ClientConnInterface) FixturePublicServiceClient {
	return &fixturePublicServiceClient{cc}
}

func (c *fixturePublicServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, FixturePublicService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FixturePublicServiceServer is the server API for FixturePublicService service.
// All implementations must embed UnimplementedFixturePublicServiceServer
// for forward compatibility.
//
// FixturePublicService 覆盖 PUBLIC 面。
type FixturePublicServiceServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedFixturePublicServiceServer()
}

// UnimplementedFixturePublicServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFixturePublicServiceServer struct{}

func (UnimplementedFixturePublicServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedFixturePublicServiceServer) mustEmbedUnimplementedFixturePublicServiceServer() {}
func (UnimplementedFixturePublicServiceServer) testEmbeddedByValue()                              {}

// UnsafeFixturePublicServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FixturePublicServiceServer will
// result in compilation errors.
type UnsafeFixturePublicServiceServer interface {
	mustEmbedUnimplementedFixturePublicServiceServer()
}

func RegisterFixturePublicServiceServer(s grpc.ServiceRegistrar, srv FixturePublicServiceServer) {
	// If the following call panics, it indicates UnimplementedFixturePublicServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FixturePublicService_ServiceDesc, srv)
}

func _FixturePublicService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FixturePublicServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FixturePublicService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FixturePublicServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FixturePublicService_ServiceDesc is the grpc.ServiceDesc for FixturePublicService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FixturePublicService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcapi.authz.testdata.v1.FixturePublicService",
	HandlerType: (*FixturePublicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _FixturePublicService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fixture.proto",
}

const (
	FixtureStreamService_WatchItems_FullMethodName = "/grpcapi.authz.testdata.v1.FixtureStreamService/WatchItems"
)

// FixtureStreamServiceClient is the client API for FixtureStreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FixtureStreamService 覆盖流式方法（Build 默认拒绝，AllowStreaming 放行）。
type FixtureStreamServiceClient interface {
	WatchItems(ctx context.Context, in *WatchItemsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchItemsResponse], error)
}

type fixtureStreamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFixtureStreamServiceClient(cc grpc.ClientConnInterface) FixtureStreamServiceClient {
	return &fixtureStreamServiceClient{cc}
}

func (c *fixtureStreamServiceClient) WatchItems(ctx context.Context, in *WatchItemsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchItemsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FixtureStreamService_ServiceDesc.Streams[0], FixtureStreamService_WatchItems_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchItemsRequest, WatchItemsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FixtureStreamService_WatchItemsClient = grpc.ServerStreamingClient[WatchItemsResponse]

// FixtureStreamServiceServer is the server API for FixtureStreamService service.
// All implementations must embed UnimplementedFixtureStreamServiceServer
// for forward compatibility.
//
// FixtureStreamService 覆盖流式方法（Build 默认拒绝，AllowStreaming 放行）。
type FixtureStreamServiceServer interface {
	WatchItems(*WatchItemsRequest, grpc.ServerStreamingServer[WatchItemsResponse]) error
	mustEmbedUnimplementedFixtureStreamServiceServer()
}

// UnimplementedFixtureStreamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFixtureStreamServiceServer struct{}

func (UnimplementedFixtureStreamServiceServer) WatchItems(*WatchItemsRequest, grpc.ServerStreamingServer[WatchItemsResponse]) error {
	return status.Error(codes.Unimplemented, "method WatchItems not implemented")
}
func (UnimplementedFixtureStreamServiceServer) mustEmbedUnimplementedFixtureStreamServiceServer() {}
func (UnimplementedFixtureStreamServiceServer) testEmbeddedByValue()                              {}

// UnsafeFixtureStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FixtureStreamServiceServer will
// result in compilation errors.
type UnsafeFixtureStreamServiceServer interface {
	mustEmbedUnimplementedFixtureStreamServiceServer()
}

func RegisterFixtureStreamServiceServer(s grpc.ServiceRegistrar, srv FixtureStreamServiceServer) {
	// If the following call panics, it indicates UnimplementedFixtureStreamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FixtureStreamService_ServiceDesc, srv)
}

func _FixtureStreamService_WatchItems_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchItemsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FixtureStreamServiceServer).WatchItems(m, &grpc.GenericServerStream[WatchItemsRequest, WatchItemsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FixtureStreamService_WatchItemsServer = grpc.ServerStreamingServer[WatchItemsResponse]

// FixtureStreamService_ServiceDesc is the grpc.ServiceDesc for FixtureStreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FixtureStreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcapi.authz.testdata.v1.FixtureStreamService",
	HandlerType: (*FixtureStreamServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchItems",
			Handler:       _FixtureStreamService_WatchItems_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "fixture.proto",
}
