// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: fixture.proto

// fixture 是 authz.Build 的合法策略夹具：以真实 FileDescriptor 驱动收集器，
// 覆盖 method_auth 优先、service_auth 回落、SERVER+scope（read/write/admin
// 三方向）、PERMISSION+permissions、PUBLIC、流式方法（配 AllowStreaming）与
// RequestFields 排序投影。故意违例的场景见 violations.proto，无 scope 声明面
// 见 plain.proto。

package testdata

import (
	_ "github.com/lynx-go/grpcapi/genproto/grpcapi/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemRequest) Reset() {
	*x = GetItemRequest{}
	mi := &file_fixture_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemRequest) ProtoMessage() {}

func (x *GetItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fixture_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemRequest.ProtoReflect.Descriptor instead.
func (*GetItemRequest) Descriptor() ([]byte, []int) {
	return file_fixture_proto_rawDescGZIP(), []int{0}
}

func (x *GetItemRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type GetItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemResponse) Reset() {
	*x = GetItemResponse{}
	mi := &file_fixture_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemResponse) ProtoMessage() {}

func (x *GetItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fixture_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemResponse.ProtoReflect.Descriptor instead.
func (*GetItemResponse) Descriptor() ([]byte, []int) {
	return file_fixture_proto_rawDescGZIP(), []int{1}
}

func (x *GetItemResponse) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type ListItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	OrderBy       string                 `protobuf:"bytes,2,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsRequest) Reset() {
	*x = ListItemsRequest{}
	mi := &file_fixture_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsRequest) ProtoMessage() {}

func (x *ListItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fixture_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsRequest.ProtoReflect.Descriptor instead.
func (*ListItemsRequest) Descriptor() ([]byte, []int) {
	return file_fixture_proto_rawDescGZIP(), []int{2}
}

func (x *ListItemsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListItemsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type ListItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemIds       []string               `protobuf:"bytes,1,rep,name=item_ids,json=itemIds,proto3" json:"item_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsResponse) Reset() {
	*x = ListItemsResponse{}
	mi := &file_fixture_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsResponse) ProtoMessage() {}

func (x *ListItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fixture_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsResponse.ProtoReflect.Descriptor instead.
func (*ListItemsResponse) Descriptor() ([]byte, []int) {
	return file_fixture_proto_rawDescGZIP(), []int{3}
}

func (x *ListItemsResponse) GetItemIds() []string {
	if x != nil {
		return x.ItemIds
	}
	return nil
}

// CreateItemRequest 字段故意乱序声明：RequestFields 投影必须按字典序输出。
type CreateItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          string                 `protobuf:"bytes,3,opt,name=tags,proto3" json:"tags,omitempty"`
	ItemId        string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateItemRequest) Reset() {
	*x = CreateItemRequest{}
	mi := &file_fixture_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemRequest) ProtoMessage() {}

func (x *CreateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fixture_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemRequest.ProtoReflect.Descriptor instead.
func (*CreateItemRequest) Descriptor() ([]byte, []int) {
	return file_fixture_proto_rawDescGZIP(), []int{4}
}

func (x *CreateItemRequest) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *CreateItemRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *CreateItemRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type CreateItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateItemResponse) Reset() {
	*x = CreateItemResponse{}
	mi := &file_fixture_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemResponse) ProtoMessage() {}

func (x *CreateItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fixture_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemResponse.ProtoReflect.Descriptor instead.
func (*CreateItemResponse) Descriptor() ([]byte, []int) {
	return file_fixture_proto_rawDescGZIP(), []int{5}
}

func (x *CreateItemResponse) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type DeleteItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemRequest) Reset() {
	*x = DeleteItemRequest{}
	mi := &file_fixture_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemRequest) ProtoMessage() {}

func (x *DeleteItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fixture_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteItemRequest) Descriptor() ([]byte, []int) {
	return file_fixture_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteItemRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type DeleteItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemResponse) Reset() {
	*x = DeleteItemResponse{}
	mi := &file_fixture_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemResponse) ProtoMessage() {}

func (x *DeleteItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fixture_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemResponse.ProtoReflect.Descriptor instead.
func (*DeleteItemResponse) Descriptor() ([]byte, []int) {
	return file_fixture_proto_rawDescGZIP(), []int{7}
}

type PurgeItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Confirm       string                 `protobuf:"bytes,1,opt,name=confirm,proto3" json:"confirm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurgeItemsRequest) Reset() {
	*x = PurgeItemsRequest{}
	mi := &file_fixture_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeItemsRequest) ProtoMessage() {}

func (x *PurgeItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fixture_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeItemsRequest.ProtoReflect.Descriptor instead.
func (*PurgeItemsRequest) Descriptor() ([]byte, []int) {
	return file_fixture_proto_rawDescGZIP(), []int{8}
}

func (x *PurgeItemsRequest) GetConfirm() string {
	if x != nil {
		return x.Confirm
	}
	return ""
}

type PurgeItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurgeItemsResponse) Reset() {
	*x = PurgeItemsResponse{}
	mi := &file_fixture_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeItemsResponse) ProtoMessage() {}

func (x *PurgeItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fixture_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeItemsResponse.ProtoReflect.Descriptor instead.
func (*PurgeItemsResponse) Descriptor() ([]byte, []int) {
	return file_fixture_proto_rawDescGZIP(), []int{9}
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_fixture_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fixture_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_fixture_proto_rawDescGZIP(), []int{10}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pong          string                 `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_fixture_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fixture_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_fixture_proto_rawDescGZIP(), []int{11}
}

func (x *PingResponse) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

type WatchItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        string                 `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchItemsRequest) Reset() {
	*x = WatchItemsRequest{}
	mi := &file_fixture_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchItemsRequest) ProtoMessage() {}

func (x *WatchItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fixture_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchItemsRequest.ProtoReflect.Descriptor instead.
func (*WatchItemsRequest) Descriptor() ([]byte, []int) {
	return file_fixture_proto_rawDescGZIP(), []int{12}
}

func (x *WatchItemsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type WatchItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchItemsResponse) Reset() {
	*x = WatchItemsResponse{}
	mi := &file_fixture_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchItemsResponse) ProtoMessage() {}

func (x *WatchItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fixture_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchItemsResponse.ProtoReflect.Descriptor instead.
func (*WatchItemsResponse) Descriptor() ([]byte, []int) {
	return file_fixture_proto_rawDescGZIP(), []int{13}
}

func (x *WatchItemsResponse) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

var File_fixture_proto protoreflect.FileDescriptor

const file_fixture_proto_rawDesc = "" +
	"\n" +
	"\rfixture.proto\x12\x19grpcapi.authz.testdata.v1\x1a\x16grpcapi/v1/authz.proto\")\n" +
	"\x0eGetItemRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\"*\n" +
	"\x0fGetItemResponse\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\"J\n" +
	"\x10ListItemsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x19\n" +
	"\border_by\x18\x02 \x01(\tR\aorderBy\".\n" +
	"\x11ListItemsResponse\x12\x19\n" +
	"\bitem_ids\x18\x01 \x03(\tR\aitemIds\"_\n" +
	"\x11CreateItemRequest\x12\x12\n" +
	"\x04tags\x18\x03 \x01(\tR\x04tags\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"-\n" +
	"\x12CreateItemResponse\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\",\n" +
	"\x11DeleteItemRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\"\x14\n" +
	"\x12DeleteItemResponse\"-\n" +
	"\x11PurgeItemsRequest\x12\x18\n" +
	"\aconfirm\x18\x01 \x01(\tR\aconfirm\"\x14\n" +
	"\x12PurgeItemsResponse\"\r\n" +
	"\vPingRequest\"\"\n" +
	"\fPingResponse\x12\x12\n" +
	"\x04pong\x18\x01 \x01(\tR\x04pong\"+\n" +
	"\x11WatchItemsRequest\x12\x16\n" +
	"\x06filter\x18\x01 \x01(\tR\x06filter\"-\n" +
	"\x12WatchItemsResponse\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId2\x90\x02\n" +
	"\x16FixturePriorityService\x12\x85\x01\n" +
	"\aGetItem\x12).grpcapi.authz.testdata.v1.GetItemRequest\x1a*.grpcapi.authz.testdata.v1.GetItemResponse\"#\xea\xc4\x19\x1f\b\x03\x1a\x05admin\x1a\x05owner\"\r\n" +
	"\tdatabases\x10\x01\x12f\n" +
	"\tListItems\x12+.grpcapi.authz.testdata.v1.ListItemsRequest\x1a,.grpcapi.authz.testdata.v1.ListItemsResponse\x1a\x06\xf2\xc4\x19\x02\b\x022\xbe\x02\n" +
	"\x14FixtureServerService\x12\x94\x01\n" +
	"\n" +
	"CreateItem\x12,.grpcapi.authz.testdata.v1.CreateItemRequest\x1a-.grpcapi.authz.testdata.v1.CreateItemResponse\")\xea\xc4\x19%\b\x03\x1a\x06member\x1a\x05admin\x1a\x05owner\"\v\n" +
	"\astorage\x10\x02\x12\x8e\x01\n" +
	"\n" +
	"DeleteItem\x12,.grpcapi.authz.testdata.v1.DeleteItemRequest\x1a-.grpcapi.authz.testdata.v1.DeleteItemResponse\"#\xea\xc4\x19\x1f\b\x03\x1a\x05admin\x1a\x05owner\"\r\n" +
	"\tdatabases\x10\x032\x94\x01\n" +
	"\x18FixturePermissionService\x12x\n" +
	"\n" +
	"PurgeItems\x12,.grpcapi.authz.testdata.v1.PurgeItemsRequest\x1a-.grpcapi.authz.testdata.v1.PurgeItemsResponse\"\r\xea\xc4\x19\t\b\x04\x12\x05owner2w\n" +
	"\x14FixturePublicService\x12_\n" +
	"\x04Ping\x12&.grpcapi.authz.testdata.v1.PingRequest\x1a'.grpcapi.authz.testdata.v1.PingResponse\"\x06\xea\xc4\x19\x02\b\x012\x9b\x01\n" +
	"\x14FixtureStreamService\x12\x82\x01\n" +
	"\n" +
	"WatchItems\x12,.grpcapi.authz.testdata.v1.WatchItemsRequest\x1a-.grpcapi.authz.testdata.v1.WatchItemsResponse\"\x15\xea\xc4\x19\x11\b\x03\"\r\n" +
	"\tdatabases\x10\x010\x01B4Z2github.com/lynx-go/grpcapi/authz/testdata;testdatab\x06proto3"

var (
	file_fixture_proto_rawDescOnce sync.Once
	file_fixture_proto_rawDescData []byte
)

func file_fixture_proto_rawDescGZIP() []byte {
	file_fixture_proto_rawDescOnce.Do(func() {
		file_fixture_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fixture_proto_rawDesc), len(file_fixture_proto_rawDesc)))
	})
	return file_fixture_proto_rawDescData
}

var file_fixture_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_fixture_proto_goTypes = []any{
	(*GetItemRequest)(nil),     // 0: grpcapi.authz.testdata.v1.GetItemRequest
	(*GetItemResponse)(nil),    // 1: grpcapi.authz.testdata.v1.GetItemResponse
	(*ListItemsRequest)(nil),   // 2: grpcapi.authz.testdata.v1.ListItemsRequest
	(*ListItemsResponse)(nil),  // 3: grpcapi.authz.testdata.v1.ListItemsResponse
	(*CreateItemRequest)(nil),  // 4: grpcapi.authz.testdata.v1.CreateItemRequest
	(*CreateItemResponse)(nil), // 5: grpcapi.authz.testdata.v1.CreateItemResponse
	(*DeleteItemRequest)(nil),  // 6: grpcapi.authz.testdata.v1.DeleteItemRequest
	(*DeleteItemResponse)(nil), // 7: grpcapi.authz.testdata.v1.DeleteItemResponse
	(*PurgeItemsRequest)(nil),  // 8: grpcapi.authz.testdata.v1.PurgeItemsRequest
	(*PurgeItemsResponse)(nil), // 9: grpcapi.authz.testdata.v1.PurgeItemsResponse
	(*PingRequest)(nil),        // 10: grpcapi.authz.testdata.v1.PingRequest
	(*PingResponse)(nil),       // 11: grpcapi.authz.testdata.v1.PingResponse
	(*WatchItemsRequest)(nil),  // 12: grpcapi.authz.testdata.v1.WatchItemsRequest
	(*WatchItemsResponse)(nil), // 13: grpcapi.authz.testdata.v1.WatchItemsResponse
}
var file_fixture_proto_depIdxs = []int32{
	0,  // 0: grpcapi.authz.testdata.v1.FixturePriorityService.GetItem:input_type -> grpcapi.authz.testdata.v1.GetItemRequest
	2,  // 1: grpcapi.authz.testdata.v1.FixturePriorityService.ListItems:input_type -> grpcapi.authz.testdata.v1.ListItemsRequest
	4,  // 2: grpcapi.authz.testdata.v1.FixtureServerService.CreateItem:input_type -> grpcapi.authz.testdata.v1.CreateItemRequest
	6,  // 3: grpcapi.authz.testdata.v1.FixtureServerService.DeleteItem:input_type -> grpcapi.authz.testdata.v1.DeleteItemRequest
	8,  // 4: grpcapi.authz.testdata.v1.FixturePermissionService.PurgeItems:input_type -> grpcapi.authz.testdata.v1.PurgeItemsRequest
	10, // 5: grpcapi.authz.testdata.v1.FixturePublicService.Ping:input_type -> grpcapi.authz.testdata.v1.PingRequest
	12, // 6: grpcapi.authz.testdata.v1.FixtureStreamService.WatchItems:input_type -> grpcapi.authz.testdata.v1.WatchItemsRequest
	1,  // 7: grpcapi.authz.testdata.v1.FixturePriorityService.GetItem:output_type -> grpcapi.authz.testdata.v1.GetItemResponse
	3,  // 8: grpcapi.authz.testdata.v1.FixturePriorityService.ListItems:output_type -> grpcapi.authz.testdata.v1.ListItemsResponse
	5,  // 9: grpcapi.authz.testdata.v1.FixtureServerService.CreateItem:output_type -> grpcapi.authz.testdata.v1.CreateItemResponse
	7,  // 10: grpcapi.authz.testdata.v1.FixtureServerService.DeleteItem:output_type -> grpcapi.authz.testdata.v1.DeleteItemResponse
	9,  // 11: grpcapi.authz.testdata.v1.FixturePermissionService.PurgeItems:output_type -> grpcapi.authz.testdata.v1.PurgeItemsResponse
	11, // 12: grpcapi.authz.testdata.v1.FixturePublicService.Ping:output_type -> grpcapi.authz.testdata.v1.PingResponse
	13, // 13: grpcapi.authz.testdata.v1.FixtureStreamService.WatchItems:output_type -> grpcapi.authz.testdata.v1.WatchItemsResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_fixture_proto_init() }
func file_fixture_proto_init() {
	if File_fixture_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fixture_proto_rawDesc), len(file_fixture_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_fixture_proto_goTypes,
		DependencyIndexes: file_fixture_proto_depIdxs,
		MessageInfos:      file_fixture_proto_msgTypes,
	}.Build()
	File_fixture_proto = out.File
	file_fixture_proto_goTypes = nil
	file_fixture_proto_depIdxs = nil
}
