// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: plain.proto

// plain 是无 scope 声明的夹具：验证「空词表 + 无 scope 声明」可正常构造
// （词表断言的跳过支），并锁定 END_USER 面权限为空时保持透传、不归一化
// （归一化是项目策略，经 Assertion 钩子注入，不进库）。

package testdata

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlainService_GetStatus_FullMethodName = "/grpcapi.authz.testdata.v1.PlainService/GetStatus"
	PlainService_GetMe_FullMethodName     = "/grpcapi.authz.testdata.v1.PlainService/GetMe"
)

// PlainServiceClient is the client API for PlainService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlainServiceClient interface {
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	// END_USER 且未声明 permissions：库内置断言不检查 END_USER 权限值域，
	// 收集层也不补位归一化。
	GetMe(ctx context.Context, in *GetMeRequest, opts ...grpc.CallOption) (*GetMeResponse, error)
}

type plainServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlainServiceClient(cc grpc.ClientConnInterface) PlainServiceClient {
	return &plainServiceClient{cc}
}

func (c *plainServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, PlainService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plainServiceClient) GetMe(ctx context.Context, in *GetMeRequest, opts ...grpc.CallOption) (*GetMeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMeResponse)
	err := c.cc.Invoke(ctx, PlainService_GetMe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlainServiceServer is the server API for PlainService service.
// All implementations must embed UnimplementedPlainServiceServer
// for forward compatibility.
type PlainServiceServer interface {
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	// END_USER 且未声明 permissions：库内置断言不检查 END_USER 权限值域，
	// 收集层也不补位归一化。
	GetMe(context.Context, *GetMeRequest) (*GetMeResponse, error)
	mustEmbedUnimplementedPlainServiceServer()
}

// UnimplementedPlainServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlainServiceServer struct{}

func (UnimplementedPlainServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedPlainServiceServer) GetMe(context.Context, *GetMeRequest) (*GetMeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMe not implemented")
}
func (UnimplementedPlainServiceServer) mustEmbedUnimplementedPlainServiceServer() {}
func (UnimplementedPlainServiceServer) testEmbeddedByValue()                      {}

// UnsafePlainServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlainServiceServer will
// result in compilation errors.
type UnsafePlainServiceServer interface {
	mustEmbedUnimplementedPlainServiceServer()
}

func RegisterPlainServiceServer(s grpc.ServiceRegistrar, srv PlainServiceServer) {
	// If the following call panics, it indicates UnimplementedPlainServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlainService_ServiceDesc, srv)
}

func _PlainService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlainServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlainService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlainServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlainService_GetMe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlainServiceServer).GetMe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlainService_GetMe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlainServiceServer).GetMe(ctx, req.(*GetMeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlainService_ServiceDesc is the grpc.ServiceDesc for PlainService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlainService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcapi.authz.testdata.v1.PlainService",
	HandlerType: (*PlainServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _PlainService_GetStatus_Handler,
		},
		{
			MethodName: "GetMe",
			Handler:    _PlainService_GetMe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plain.proto",
}
