// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: plain.proto

// plain 是无 scope 声明的夹具：验证「空词表 + 无 scope 声明」可正常构造
// （词表断言的跳过支），并锁定 END_USER 面权限为空时保持透传、不归一化
// （归一化是项目策略，经 Assertion 钩子注入，不进库）。

package testdata

import (
	_ "github.com/lynx-go/grpcapi/genproto/grpcapi/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_plain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_plain_proto_rawDescGZIP(), []int{0}
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_plain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_plain_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetMeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeRequest) Reset() {
	*x = GetMeRequest{}
	mi := &file_plain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeRequest) ProtoMessage() {}

func (x *GetMeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeRequest.ProtoReflect.Descriptor instead.
func (*GetMeRequest) Descriptor() ([]byte, []int) {
	return file_plain_proto_rawDescGZIP(), []int{2}
}

type GetMeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeResponse) Reset() {
	*x = GetMeResponse{}
	mi := &file_plain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeResponse) ProtoMessage() {}

func (x *GetMeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeResponse.ProtoReflect.Descriptor instead.
func (*GetMeResponse) Descriptor() ([]byte, []int) {
	return file_plain_proto_rawDescGZIP(), []int{3}
}

func (x *GetMeResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_plain_proto protoreflect.FileDescriptor

const file_plain_proto_rawDesc = "" +
	"\n" +
	"\vplain.proto\x12\x19grpcapi.authz.testdata.v1\x1a\x16grpcapi/v1/authz.proto\"\x12\n" +
	"\x10GetStatusRequest\"+\n" +
	"\x11GetStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x0e\n" +
	"\fGetMeRequest\"(\n" +
	"\rGetMeResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId2\xe2\x01\n" +
	"\fPlainService\x12n\n" +
	"\tGetStatus\x12+.grpcapi.authz.testdata.v1.GetStatusRequest\x1a,.grpcapi.authz.testdata.v1.GetStatusResponse\"\x06\xea\xc4\x19\x02\b\x01\x12b\n" +
	"\x05GetMe\x12'.grpcapi.authz.testdata.v1.GetMeRequest\x1a(.grpcapi.authz.testdata.v1.GetMeResponse\"\x06\xea\xc4\x19\x02\b\x02B4Z2github.com/lynx-go/grpcapi/authz/testdata;testdatab\x06proto3"

var (
	file_plain_proto_rawDescOnce sync.Once
	file_plain_proto_rawDescData []byte
)

func file_plain_proto_rawDescGZIP() []byte {
	file_plain_proto_rawDescOnce.Do(func() {
		file_plain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plain_proto_rawDesc), len(file_plain_proto_rawDesc)))
	})
	return file_plain_proto_rawDescData
}

var file_plain_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_plain_proto_goTypes = []any{
	(*GetStatusRequest)(nil),  // 0: grpcapi.authz.testdata.v1.GetStatusRequest
	(*GetStatusResponse)(nil), // 1: grpcapi.authz.testdata.v1.GetStatusResponse
	(*GetMeRequest)(nil),      // 2: grpcapi.authz.testdata.v1.GetMeRequest
	(*GetMeResponse)(nil),     // 3: grpcapi.authz.testdata.v1.GetMeResponse
}
var file_plain_proto_depIdxs = []int32{
	0, // 0: grpcapi.authz.testdata.v1.PlainService.GetStatus:input_type -> grpcapi.authz.testdata.v1.GetStatusRequest
	2, // 1: grpcapi.authz.testdata.v1.PlainService.GetMe:input_type -> grpcapi.authz.testdata.v1.GetMeRequest
	1, // 2: grpcapi.authz.testdata.v1.PlainService.GetStatus:output_type -> grpcapi.authz.testdata.v1.GetStatusResponse
	3, // 3: grpcapi.authz.testdata.v1.PlainService.GetMe:output_type -> grpcapi.authz.testdata.v1.GetMeResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_plain_proto_init() }
func file_plain_proto_init() {
	if File_plain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plain_proto_rawDesc), len(file_plain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plain_proto_goTypes,
		DependencyIndexes: file_plain_proto_depIdxs,
		MessageInfos:      file_plain_proto_msgTypes,
	}.Build()
	File_plain_proto = out.File
	file_plain_proto_goTypes = nil
	file_plain_proto_depIdxs = nil
}
