// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: violations.proto

// violations 是 authz 内置断言的违例夹具：每个 service 精确触发一条内置断言
//（断言编号对应 authz.Build 文档注释）。整文件驱动 Build 时全部违例聚合进
// 同一 error——聚合语义测试直接全量断言。本文件不含合法用例，合法面见
// fixture.proto。

package testdata

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BadMissingPolicyService_GetMissingPolicy_FullMethodName = "/grpcapi.authz.testdata.v1.BadMissingPolicyService/GetMissingPolicy"
)

// BadMissingPolicyServiceClient is the client API for BadMissingPolicyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 断言 1：完全未声明（无 method_auth 且服务无 default_access）。
type BadMissingPolicyServiceClient interface {
	GetMissingPolicy(ctx context.Context, in *GetMissingPolicyRequest, opts ...grpc.CallOption) (*GetMissingPolicyResponse, error)
}

type badMissingPolicyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBadMissingPolicyServiceClient(cc grpc.ClientConnInterface) BadMissingPolicyServiceClient {
	return &badMissingPolicyServiceClient{cc}
}

func (c *badMissingPolicyServiceClient) GetMissingPolicy(ctx context.Context, in *GetMissingPolicyRequest, opts ...grpc.CallOption) (*GetMissingPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMissingPolicyResponse)
	err := c.cc.Invoke(ctx, BadMissingPolicyService_GetMissingPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BadMissingPolicyServiceServer is the server API for BadMissingPolicyService service.
// All implementations must embed UnimplementedBadMissingPolicyServiceServer
// for forward compatibility.
//
// 断言 1：完全未声明（无 method_auth 且服务无 default_access）。
type BadMissingPolicyServiceServer interface {
	GetMissingPolicy(context.Context, *GetMissingPolicyRequest) (*GetMissingPolicyResponse, error)
	mustEmbedUnimplementedBadMissingPolicyServiceServer()
}

// UnimplementedBadMissingPolicyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBadMissingPolicyServiceServer struct{}

func (UnimplementedBadMissingPolicyServiceServer) GetMissingPolicy(context.Context, *GetMissingPolicyRequest) (*GetMissingPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMissingPolicy not implemented")
}
func (UnimplementedBadMissingPolicyServiceServer) mustEmbedUnimplementedBadMissingPolicyServiceServer() {
}
func (UnimplementedBadMissingPolicyServiceServer) testEmbeddedByValue() {}

// UnsafeBadMissingPolicyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BadMissingPolicyServiceServer will
// result in compilation errors.
type UnsafeBadMissingPolicyServiceServer interface {
	mustEmbedUnimplementedBadMissingPolicyServiceServer()
}

func RegisterBadMissingPolicyServiceServer(s grpc.ServiceRegistrar, srv BadMissingPolicyServiceServer) {
	// If the following call panics, it indicates UnimplementedBadMissingPolicyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BadMissingPolicyService_ServiceDesc, srv)
}

func _BadMissingPolicyService_GetMissingPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMissingPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BadMissingPolicyServiceServer).GetMissingPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BadMissingPolicyService_GetMissingPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BadMissingPolicyServiceServer).GetMissingPolicy(ctx, req.(*GetMissingPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BadMissingPolicyService_ServiceDesc is the grpc.ServiceDesc for BadMissingPolicyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BadMissingPolicyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcapi.authz.testdata.v1.BadMissingPolicyService",
	HandlerType: (*BadMissingPolicyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMissingPolicy",
			Handler:    _BadMissingPolicyService_GetMissingPolicy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "violations.proto",
}

const (
	BadUnspecifiedService_GetUnspecified_FullMethodName = "/grpcapi.authz.testdata.v1.BadUnspecifiedService/GetUnspecified"
)

// BadUnspecifiedServiceClient is the client API for BadUnspecifiedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 断言 1：显式 UNSPECIFIED（服务同样无缺省档可回落）。
type BadUnspecifiedServiceClient interface {
	GetUnspecified(ctx context.Context, in *GetUnspecifiedRequest, opts ...grpc.CallOption) (*GetUnspecifiedResponse, error)
}

type badUnspecifiedServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBadUnspecifiedServiceClient(cc grpc.ClientConnInterface) BadUnspecifiedServiceClient {
	return &badUnspecifiedServiceClient{cc}
}

func (c *badUnspecifiedServiceClient) GetUnspecified(ctx context.Context, in *GetUnspecifiedRequest, opts ...grpc.CallOption) (*GetUnspecifiedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUnspecifiedResponse)
	err := c.cc.Invoke(ctx, BadUnspecifiedService_GetUnspecified_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BadUnspecifiedServiceServer is the server API for BadUnspecifiedService service.
// All implementations must embed UnimplementedBadUnspecifiedServiceServer
// for forward compatibility.
//
// 断言 1：显式 UNSPECIFIED（服务同样无缺省档可回落）。
type BadUnspecifiedServiceServer interface {
	GetUnspecified(context.Context, *GetUnspecifiedRequest) (*GetUnspecifiedResponse, error)
	mustEmbedUnimplementedBadUnspecifiedServiceServer()
}

// UnimplementedBadUnspecifiedServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBadUnspecifiedServiceServer struct{}

func (UnimplementedBadUnspecifiedServiceServer) GetUnspecified(context.Context, *GetUnspecifiedRequest) (*GetUnspecifiedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUnspecified not implemented")
}
func (UnimplementedBadUnspecifiedServiceServer) mustEmbedUnimplementedBadUnspecifiedServiceServer() {}
func (UnimplementedBadUnspecifiedServiceServer) testEmbeddedByValue()                               {}

// UnsafeBadUnspecifiedServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BadUnspecifiedServiceServer will
// result in compilation errors.
type UnsafeBadUnspecifiedServiceServer interface {
	mustEmbedUnimplementedBadUnspecifiedServiceServer()
}

func RegisterBadUnspecifiedServiceServer(s grpc.ServiceRegistrar, srv BadUnspecifiedServiceServer) {
	// If the following call panics, it indicates UnimplementedBadUnspecifiedServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BadUnspecifiedService_ServiceDesc, srv)
}

func _BadUnspecifiedService_GetUnspecified_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUnspecifiedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BadUnspecifiedServiceServer).GetUnspecified(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BadUnspecifiedService_GetUnspecified_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BadUnspecifiedServiceServer).GetUnspecified(ctx, req.(*GetUnspecifiedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BadUnspecifiedService_ServiceDesc is the grpc.ServiceDesc for BadUnspecifiedService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BadUnspecifiedService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcapi.authz.testdata.v1.BadUnspecifiedService",
	HandlerType: (*BadUnspecifiedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUnspecified",
			Handler:    _BadUnspecifiedService_GetUnspecified_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "violations.proto",
}

const (
	BadServerNoScopeService_GetServerNoScope_FullMethodName = "/grpcapi.authz.testdata.v1.BadServerNoScopeService/GetServerNoScope"
)

// BadServerNoScopeServiceClient is the client API for BadServerNoScopeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 断言 2：SERVER 面未声明 api_key_scope。
type BadServerNoScopeServiceClient interface {
	GetServerNoScope(ctx context.Context, in *GetServerNoScopeRequest, opts ...grpc.CallOption) (*GetServerNoScopeResponse, error)
}

type badServerNoScopeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBadServerNoScopeServiceClient(cc grpc.ClientConnInterface) BadServerNoScopeServiceClient {
	return &badServerNoScopeServiceClient{cc}
}

func (c *badServerNoScopeServiceClient) GetServerNoScope(ctx context.Context, in *GetServerNoScopeRequest, opts ...grpc.CallOption) (*GetServerNoScopeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServerNoScopeResponse)
	err := c.cc.Invoke(ctx, BadServerNoScopeService_GetServerNoScope_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BadServerNoScopeServiceServer is the server API for BadServerNoScopeService service.
// All implementations must embed UnimplementedBadServerNoScopeServiceServer
// for forward compatibility.
//
// 断言 2：SERVER 面未声明 api_key_scope。
type BadServerNoScopeServiceServer interface {
	GetServerNoScope(context.Context, *GetServerNoScopeRequest) (*GetServerNoScopeResponse, error)
	mustEmbedUnimplementedBadServerNoScopeServiceServer()
}

// UnimplementedBadServerNoScopeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBadServerNoScopeServiceServer struct{}

func (UnimplementedBadServerNoScopeServiceServer) GetServerNoScope(context.Context, *GetServerNoScopeRequest) (*GetServerNoScopeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServerNoScope not implemented")
}
func (UnimplementedBadServerNoScopeServiceServer) mustEmbedUnimplementedBadServerNoScopeServiceServer() {
}
func (UnimplementedBadServerNoScopeServiceServer) testEmbeddedByValue() {}

// UnsafeBadServerNoScopeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BadServerNoScopeServiceServer will
// result in compilation errors.
type UnsafeBadServerNoScopeServiceServer interface {
	mustEmbedUnimplementedBadServerNoScopeServiceServer()
}

func RegisterBadServerNoScopeServiceServer(s grpc.ServiceRegistrar, srv BadServerNoScopeServiceServer) {
	// If the following call panics, it indicates UnimplementedBadServerNoScopeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BadServerNoScopeService_ServiceDesc, srv)
}

func _BadServerNoScopeService_GetServerNoScope_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerNoScopeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BadServerNoScopeServiceServer).GetServerNoScope(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BadServerNoScopeService_GetServerNoScope_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BadServerNoScopeServiceServer).GetServerNoScope(ctx, req.(*GetServerNoScopeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BadServerNoScopeService_ServiceDesc is the grpc.ServiceDesc for BadServerNoScopeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BadServerNoScopeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcapi.authz.testdata.v1.BadServerNoScopeService",
	HandlerType: (*BadServerNoScopeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServerNoScope",
			Handler:    _BadServerNoScopeService_GetServerNoScope_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "violations.proto",
}

const (
	BadPermissionNoPermsService_GetPermissionNoPerms_FullMethodName = "/grpcapi.authz.testdata.v1.BadPermissionNoPermsService/GetPermissionNoPerms"
)

// BadPermissionNoPermsServiceClient is the client API for BadPermissionNoPermsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 断言 3：经 service_auth 回落到 PERMISSION 且未声明 permissions。
type BadPermissionNoPermsServiceClient interface {
	GetPermissionNoPerms(ctx context.Context, in *GetPermissionNoPermsRequest, opts ...grpc.CallOption) (*GetPermissionNoPermsResponse, error)
}

type badPermissionNoPermsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBadPermissionNoPermsServiceClient(cc grpc.ClientConnInterface) BadPermissionNoPermsServiceClient {
	return &badPermissionNoPermsServiceClient{cc}
}

func (c *badPermissionNoPermsServiceClient) GetPermissionNoPerms(ctx context.Context, in *GetPermissionNoPermsRequest, opts ...grpc.CallOption) (*GetPermissionNoPermsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPermissionNoPermsResponse)
	err := c.cc.Invoke(ctx, BadPermissionNoPermsService_GetPermissionNoPerms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BadPermissionNoPermsServiceServer is the server API for BadPermissionNoPermsService service.
// All implementations must embed UnimplementedBadPermissionNoPermsServiceServer
// for forward compatibility.
//
// 断言 3：经 service_auth 回落到 PERMISSION 且未声明 permissions。
type BadPermissionNoPermsServiceServer interface {
	GetPermissionNoPerms(context.Context, *GetPermissionNoPermsRequest) (*GetPermissionNoPermsResponse, error)
	mustEmbedUnimplementedBadPermissionNoPermsServiceServer()
}

// UnimplementedBadPermissionNoPermsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBadPermissionNoPermsServiceServer struct{}

func (UnimplementedBadPermissionNoPermsServiceServer) GetPermissionNoPerms(context.Context, *GetPermissionNoPermsRequest) (*GetPermissionNoPermsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPermissionNoPerms not implemented")
}
func (UnimplementedBadPermissionNoPermsServiceServer) mustEmbedUnimplementedBadPermissionNoPermsServiceServer() {
}
func (UnimplementedBadPermissionNoPermsServiceServer) testEmbeddedByValue() {}

// UnsafeBadPermissionNoPermsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BadPermissionNoPermsServiceServer will
// result in compilation errors.
type UnsafeBadPermissionNoPermsServiceServer interface {
	mustEmbedUnimplementedBadPermissionNoPermsServiceServer()
}

func RegisterBadPermissionNoPermsServiceServer(s grpc.ServiceRegistrar, srv BadPermissionNoPermsServiceServer) {
	// If the following call panics, it indicates UnimplementedBadPermissionNoPermsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BadPermissionNoPermsService_ServiceDesc, srv)
}

func _BadPermissionNoPermsService_GetPermissionNoPerms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPermissionNoPermsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BadPermissionNoPermsServiceServer).GetPermissionNoPerms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BadPermissionNoPermsService_GetPermissionNoPerms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BadPermissionNoPermsServiceServer).GetPermissionNoPerms(ctx, req.(*GetPermissionNoPermsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BadPermissionNoPermsService_ServiceDesc is the grpc.ServiceDesc for BadPermissionNoPermsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BadPermissionNoPermsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcapi.authz.testdata.v1.BadPermissionNoPermsService",
	HandlerType: (*BadPermissionNoPermsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPermissionNoPerms",
			Handler:    _BadPermissionNoPermsService_GetPermissionNoPerms_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "violations.proto",
}

const (
	BadSystemService_GetSystem_FullMethodName = "/grpcapi.authz.testdata.v1.BadSystemService/GetSystem"
)

// BadSystemServiceClient is the client API for BadSystemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 断言 4：SYSTEM 档位 v1 禁用。
type BadSystemServiceClient interface {
	GetSystem(ctx context.Context, in *GetSystemRequest, opts ...grpc.CallOption) (*GetSystemResponse, error)
}

type badSystemServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBadSystemServiceClient(cc grpc.ClientConnInterface) BadSystemServiceClient {
	return &badSystemServiceClient{cc}
}

func (c *badSystemServiceClient) GetSystem(ctx context.Context, in *GetSystemRequest, opts ...grpc.CallOption) (*GetSystemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSystemResponse)
	err := c.cc.Invoke(ctx, BadSystemService_GetSystem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BadSystemServiceServer is the server API for BadSystemService service.
// All implementations must embed UnimplementedBadSystemServiceServer
// for forward compatibility.
//
// 断言 4：SYSTEM 档位 v1 禁用。
type BadSystemServiceServer interface {
	GetSystem(context.Context, *GetSystemRequest) (*GetSystemResponse, error)
	mustEmbedUnimplementedBadSystemServiceServer()
}

// UnimplementedBadSystemServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBadSystemServiceServer struct{}

func (UnimplementedBadSystemServiceServer) GetSystem(context.Context, *GetSystemRequest) (*GetSystemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSystem not implemented")
}
func (UnimplementedBadSystemServiceServer) mustEmbedUnimplementedBadSystemServiceServer() {}
func (UnimplementedBadSystemServiceServer) testEmbeddedByValue()                          {}

// UnsafeBadSystemServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BadSystemServiceServer will
// result in compilation errors.
type UnsafeBadSystemServiceServer interface {
	mustEmbedUnimplementedBadSystemServiceServer()
}

func RegisterBadSystemServiceServer(s grpc.ServiceRegistrar, srv BadSystemServiceServer) {
	// If the following call panics, it indicates UnimplementedBadSystemServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BadSystemService_ServiceDesc, srv)
}

func _BadSystemService_GetSystem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSystemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BadSystemServiceServer).GetSystem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BadSystemService_GetSystem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BadSystemServiceServer).GetSystem(ctx, req.(*GetSystemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BadSystemService_ServiceDesc is the grpc.ServiceDesc for BadSystemService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BadSystemService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcapi.authz.testdata.v1.BadSystemService",
	HandlerType: (*BadSystemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSystem",
			Handler:    _BadSystemService_GetSystem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "violations.proto",
}

const (
	BadAlienScopeService_GetAlienScope_FullMethodName = "/grpcapi.authz.testdata.v1.BadAlienScopeService/GetAlienScope"
)

// BadAlienScopeServiceClient is the client API for BadAlienScopeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 断言 6：scope 资源在词表外（alien 不在 {databases, storage} 中）。
type BadAlienScopeServiceClient interface {
	GetAlienScope(ctx context.Context, in *GetAlienScopeRequest, opts ...grpc.CallOption) (*GetAlienScopeResponse, error)
}

type badAlienScopeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBadAlienScopeServiceClient(cc grpc.ClientConnInterface) BadAlienScopeServiceClient {
	return &badAlienScopeServiceClient{cc}
}

func (c *badAlienScopeServiceClient) GetAlienScope(ctx context.Context, in *GetAlienScopeRequest, opts ...grpc.CallOption) (*GetAlienScopeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAlienScopeResponse)
	err := c.cc.Invoke(ctx, BadAlienScopeService_GetAlienScope_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BadAlienScopeServiceServer is the server API for BadAlienScopeService service.
// All implementations must embed UnimplementedBadAlienScopeServiceServer
// for forward compatibility.
//
// 断言 6：scope 资源在词表外（alien 不在 {databases, storage} 中）。
type BadAlienScopeServiceServer interface {
	GetAlienScope(context.Context, *GetAlienScopeRequest) (*GetAlienScopeResponse, error)
	mustEmbedUnimplementedBadAlienScopeServiceServer()
}

// UnimplementedBadAlienScopeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBadAlienScopeServiceServer struct{}

func (UnimplementedBadAlienScopeServiceServer) GetAlienScope(context.Context, *GetAlienScopeRequest) (*GetAlienScopeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAlienScope not implemented")
}
func (UnimplementedBadAlienScopeServiceServer) mustEmbedUnimplementedBadAlienScopeServiceServer() {}
func (UnimplementedBadAlienScopeServiceServer) testEmbeddedByValue()                              {}

// UnsafeBadAlienScopeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BadAlienScopeServiceServer will
// result in compilation errors.
type UnsafeBadAlienScopeServiceServer interface {
	mustEmbedUnimplementedBadAlienScopeServiceServer()
}

func RegisterBadAlienScopeServiceServer(s grpc.ServiceRegistrar, srv BadAlienScopeServiceServer) {
	// If the following call panics, it indicates UnimplementedBadAlienScopeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BadAlienScopeService_ServiceDesc, srv)
}

func _BadAlienScopeService_GetAlienScope_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlienScopeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BadAlienScopeServiceServer).GetAlienScope(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BadAlienScopeService_GetAlienScope_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BadAlienScopeServiceServer).GetAlienScope(ctx, req.(*GetAlienScopeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BadAlienScopeService_ServiceDesc is the grpc.ServiceDesc for BadAlienScopeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BadAlienScopeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcapi.authz.testdata.v1.BadAlienScopeService",
	HandlerType: (*BadAlienScopeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAlienScope",
			Handler:    _BadAlienScopeService_GetAlienScope_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "violations.proto",
}

const (
	BadOplessScopeService_GetOplessScope_FullMethodName = "/grpcapi.authz.testdata.v1.BadOplessScopeService/GetOplessScope"
)

// BadOplessScopeServiceClient is the client API for BadOplessScopeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 断言 7：api_key_scope.op 未声明（UNSPECIFIED）。
type BadOplessScopeServiceClient interface {
	GetOplessScope(ctx context.Context, in *GetOplessScopeRequest, opts ...grpc.CallOption) (*GetOplessScopeResponse, error)
}

type badOplessScopeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBadOplessScopeServiceClient(cc grpc.ClientConnInterface) BadOplessScopeServiceClient {
	return &badOplessScopeServiceClient{cc}
}

func (c *badOplessScopeServiceClient) GetOplessScope(ctx context.Context, in *GetOplessScopeRequest, opts ...grpc.CallOption) (*GetOplessScopeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOplessScopeResponse)
	err := c.cc.Invoke(ctx, BadOplessScopeService_GetOplessScope_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BadOplessScopeServiceServer is the server API for BadOplessScopeService service.
// All implementations must embed UnimplementedBadOplessScopeServiceServer
// for forward compatibility.
//
// 断言 7：api_key_scope.op 未声明（UNSPECIFIED）。
type BadOplessScopeServiceServer interface {
	GetOplessScope(context.Context, *GetOplessScopeRequest) (*GetOplessScopeResponse, error)
	mustEmbedUnimplementedBadOplessScopeServiceServer()
}

// UnimplementedBadOplessScopeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBadOplessScopeServiceServer struct{}

func (UnimplementedBadOplessScopeServiceServer) GetOplessScope(context.Context, *GetOplessScopeRequest) (*GetOplessScopeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOplessScope not implemented")
}
func (UnimplementedBadOplessScopeServiceServer) mustEmbedUnimplementedBadOplessScopeServiceServer() {}
func (UnimplementedBadOplessScopeServiceServer) testEmbeddedByValue()                               {}

// UnsafeBadOplessScopeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BadOplessScopeServiceServer will
// result in compilation errors.
type UnsafeBadOplessScopeServiceServer interface {
	mustEmbedUnimplementedBadOplessScopeServiceServer()
}

func RegisterBadOplessScopeServiceServer(s grpc.ServiceRegistrar, srv BadOplessScopeServiceServer) {
	// If the following call panics, it indicates UnimplementedBadOplessScopeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BadOplessScopeService_ServiceDesc, srv)
}

func _BadOplessScopeService_GetOplessScope_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOplessScopeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BadOplessScopeServiceServer).GetOplessScope(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BadOplessScopeService_GetOplessScope_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BadOplessScopeServiceServer).GetOplessScope(ctx, req.(*GetOplessScopeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BadOplessScopeService_ServiceDesc is the grpc.ServiceDesc for BadOplessScopeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BadOplessScopeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcapi.authz.testdata.v1.BadOplessScopeService",
	HandlerType: (*BadOplessScopeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOplessScope",
			Handler:    _BadOplessScopeService_GetOplessScope_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "violations.proto",
}
