// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: violations.proto

// violations 是 authz 内置断言的违例夹具：每个 service 精确触发一条内置断言
//（断言编号对应 authz.Build 文档注释）。整文件驱动 Build 时全部违例聚合进
// 同一 error——聚合语义测试直接全量断言。本文件不含合法用例，合法面见
// fixture.proto。

package testdata

import (
	_ "github.com/lynx-go/grpcapi/genproto/grpcapi/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMissingPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMissingPolicyRequest) Reset() {
	*x = GetMissingPolicyRequest{}
	mi := &file_violations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMissingPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMissingPolicyRequest) ProtoMessage() {}

func (x *GetMissingPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_violations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMissingPolicyRequest.ProtoReflect.Descriptor instead.
func (*GetMissingPolicyRequest) Descriptor() ([]byte, []int) {
	return file_violations_proto_rawDescGZIP(), []int{0}
}

func (x *GetMissingPolicyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMissingPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMissingPolicyResponse) Reset() {
	*x = GetMissingPolicyResponse{}
	mi := &file_violations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMissingPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMissingPolicyResponse) ProtoMessage() {}

func (x *GetMissingPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_violations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMissingPolicyResponse.ProtoReflect.Descriptor instead.
func (*GetMissingPolicyResponse) Descriptor() ([]byte, []int) {
	return file_violations_proto_rawDescGZIP(), []int{1}
}

type GetUnspecifiedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnspecifiedRequest) Reset() {
	*x = GetUnspecifiedRequest{}
	mi := &file_violations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnspecifiedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnspecifiedRequest) ProtoMessage() {}

func (x *GetUnspecifiedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_violations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnspecifiedRequest.ProtoReflect.Descriptor instead.
func (*GetUnspecifiedRequest) Descriptor() ([]byte, []int) {
	return file_violations_proto_rawDescGZIP(), []int{2}
}

func (x *GetUnspecifiedRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUnspecifiedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnspecifiedResponse) Reset() {
	*x = GetUnspecifiedResponse{}
	mi := &file_violations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnspecifiedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnspecifiedResponse) ProtoMessage() {}

func (x *GetUnspecifiedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_violations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnspecifiedResponse.ProtoReflect.Descriptor instead.
func (*GetUnspecifiedResponse) Descriptor() ([]byte, []int) {
	return file_violations_proto_rawDescGZIP(), []int{3}
}

type GetServerNoScopeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerNoScopeRequest) Reset() {
	*x = GetServerNoScopeRequest{}
	mi := &file_violations_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerNoScopeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerNoScopeRequest) ProtoMessage() {}

func (x *GetServerNoScopeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_violations_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerNoScopeRequest.ProtoReflect.Descriptor instead.
func (*GetServerNoScopeRequest) Descriptor() ([]byte, []int) {
	return file_violations_proto_rawDescGZIP(), []int{4}
}

func (x *GetServerNoScopeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetServerNoScopeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerNoScopeResponse) Reset() {
	*x = GetServerNoScopeResponse{}
	mi := &file_violations_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerNoScopeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerNoScopeResponse) ProtoMessage() {}

func (x *GetServerNoScopeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_violations_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerNoScopeResponse.ProtoReflect.Descriptor instead.
func (*GetServerNoScopeResponse) Descriptor() ([]byte, []int) {
	return file_violations_proto_rawDescGZIP(), []int{5}
}

type GetPermissionNoPermsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermissionNoPermsRequest) Reset() {
	*x = GetPermissionNoPermsRequest{}
	mi := &file_violations_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionNoPermsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionNoPermsRequest) ProtoMessage() {}

func (x *GetPermissionNoPermsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_violations_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionNoPermsRequest.ProtoReflect.Descriptor instead.
func (*GetPermissionNoPermsRequest) Descriptor() ([]byte, []int) {
	return file_violations_proto_rawDescGZIP(), []int{6}
}

func (x *GetPermissionNoPermsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPermissionNoPermsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermissionNoPermsResponse) Reset() {
	*x = GetPermissionNoPermsResponse{}
	mi := &file_violations_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionNoPermsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionNoPermsResponse) ProtoMessage() {}

func (x *GetPermissionNoPermsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_violations_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionNoPermsResponse.ProtoReflect.Descriptor instead.
func (*GetPermissionNoPermsResponse) Descriptor() ([]byte, []int) {
	return file_violations_proto_rawDescGZIP(), []int{7}
}

type GetSystemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemRequest) Reset() {
	*x = GetSystemRequest{}
	mi := &file_violations_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemRequest) ProtoMessage() {}

func (x *GetSystemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_violations_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemRequest.ProtoReflect.Descriptor instead.
func (*GetSystemRequest) Descriptor() ([]byte, []int) {
	return file_violations_proto_rawDescGZIP(), []int{8}
}

func (x *GetSystemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetSystemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemResponse) Reset() {
	*x = GetSystemResponse{}
	mi := &file_violations_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemResponse) ProtoMessage() {}

func (x *GetSystemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_violations_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemResponse.ProtoReflect.Descriptor instead.
func (*GetSystemResponse) Descriptor() ([]byte, []int) {
	return file_violations_proto_rawDescGZIP(), []int{9}
}

type GetAlienScopeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlienScopeRequest) Reset() {
	*x = GetAlienScopeRequest{}
	mi := &file_violations_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlienScopeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlienScopeRequest) ProtoMessage() {}

func (x *GetAlienScopeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_violations_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlienScopeRequest.ProtoReflect.Descriptor instead.
func (*GetAlienScopeRequest) Descriptor() ([]byte, []int) {
	return file_violations_proto_rawDescGZIP(), []int{10}
}

func (x *GetAlienScopeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAlienScopeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlienScopeResponse) Reset() {
	*x = GetAlienScopeResponse{}
	mi := &file_violations_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlienScopeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlienScopeResponse) ProtoMessage() {}

func (x *GetAlienScopeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_violations_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlienScopeResponse.ProtoReflect.Descriptor instead.
func (*GetAlienScopeResponse) Descriptor() ([]byte, []int) {
	return file_violations_proto_rawDescGZIP(), []int{11}
}

type GetOplessScopeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOplessScopeRequest) Reset() {
	*x = GetOplessScopeRequest{}
	mi := &file_violations_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOplessScopeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOplessScopeRequest) ProtoMessage() {}

func (x *GetOplessScopeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_violations_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOplessScopeRequest.ProtoReflect.Descriptor instead.
func (*GetOplessScopeRequest) Descriptor() ([]byte, []int) {
	return file_violations_proto_rawDescGZIP(), []int{12}
}

func (x *GetOplessScopeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetOplessScopeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOplessScopeResponse) Reset() {
	*x = GetOplessScopeResponse{}
	mi := &file_violations_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOplessScopeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOplessScopeResponse) ProtoMessage() {}

func (x *GetOplessScopeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_violations_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOplessScopeResponse.ProtoReflect.Descriptor instead.
func (*GetOplessScopeResponse) Descriptor() ([]byte, []int) {
	return file_violations_proto_rawDescGZIP(), []int{13}
}

var File_violations_proto protoreflect.FileDescriptor

const file_violations_proto_rawDesc = "" +
	"\n" +
	"\x10violations.proto\x12\x19grpcapi.authz.testdata.v1\x1a\x16grpcapi/v1/authz.proto\")\n" +
	"\x17GetMissingPolicyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1a\n" +
	"\x18GetMissingPolicyResponse\"'\n" +
	"\x15GetUnspecifiedRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x18\n" +
	"\x16GetUnspecifiedResponse\")\n" +
	"\x17GetServerNoScopeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1a\n" +
	"\x18GetServerNoScopeResponse\"-\n" +
	"\x1bGetPermissionNoPermsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1e\n" +
	"\x1cGetPermissionNoPermsResponse\"\"\n" +
	"\x10GetSystemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x13\n" +
	"\x11GetSystemResponse\"&\n" +
	"\x14GetAlienScopeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x17\n" +
	"\x15GetAlienScopeResponse\"'\n" +
	"\x15GetOplessScopeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x18\n" +
	"\x16GetOplessScopeResponse2\x96\x01\n" +
	"\x17BadMissingPolicyService\x12{\n" +
	"\x10GetMissingPolicy\x122.grpcapi.authz.testdata.v1.GetMissingPolicyRequest\x1a3.grpcapi.authz.testdata.v1.GetMissingPolicyResponse2\x94\x01\n" +
	"\x15BadUnspecifiedService\x12{\n" +
	"\x0eGetUnspecified\x120.grpcapi.authz.testdata.v1.GetUnspecifiedRequest\x1a1.grpcapi.authz.testdata.v1.GetUnspecifiedResponse\"\x04\xea\xc4\x19\x002\x9f\x01\n" +
	"\x17BadServerNoScopeService\x12\x83\x01\n" +
	"\x10GetServerNoScope\x122.grpcapi.authz.testdata.v1.GetServerNoScopeRequest\x1a3.grpcapi.authz.testdata.v1.GetServerNoScopeResponse\"\x06\xea\xc4\x19\x02\b\x032\xaf\x01\n" +
	"\x1bBadPermissionNoPermsService\x12\x87\x01\n" +
	"\x14GetPermissionNoPerms\x126.grpcapi.authz.testdata.v1.GetPermissionNoPermsRequest\x1a7.grpcapi.authz.testdata.v1.GetPermissionNoPermsResponse\x1a\x06\xf2\xc4\x19\x02\b\x042\x82\x01\n" +
	"\x10BadSystemService\x12f\n" +
	"\tGetSystem\x12+.grpcapi.authz.testdata.v1.GetSystemRequest\x1a,.grpcapi.authz.testdata.v1.GetSystemResponse\x1a\x06\xf2\xc4\x19\x02\b\x052\x9e\x01\n" +
	"\x14BadAlienScopeService\x12\x85\x01\n" +
	"\rGetAlienScope\x12/.grpcapi.authz.testdata.v1.GetAlienScopeRequest\x1a0.grpcapi.authz.testdata.v1.GetAlienScopeResponse\"\x11\xea\xc4\x19\r\b\x03\"\t\n" +
	"\x05alien\x10\x012\xa4\x01\n" +
	"\x15BadOplessScopeService\x12\x8a\x01\n" +
	"\x0eGetOplessScope\x120.grpcapi.authz.testdata.v1.GetOplessScopeRequest\x1a1.grpcapi.authz.testdata.v1.GetOplessScopeResponse\"\x13\xea\xc4\x19\x0f\b\x03\"\v\n" +
	"\tdatabasesB4Z2github.com/lynx-go/grpcapi/authz/testdata;testdatab\x06proto3"

var (
	file_violations_proto_rawDescOnce sync.Once
	file_violations_proto_rawDescData []byte
)

func file_violations_proto_rawDescGZIP() []byte {
	file_violations_proto_rawDescOnce.Do(func() {
		file_violations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_violations_proto_rawDesc), len(file_violations_proto_rawDesc)))
	})
	return file_violations_proto_rawDescData
}

var file_violations_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_violations_proto_goTypes = []any{
	(*GetMissingPolicyRequest)(nil),      // 0: grpcapi.authz.testdata.v1.GetMissingPolicyRequest
	(*GetMissingPolicyResponse)(nil),     // 1: grpcapi.authz.testdata.v1.GetMissingPolicyResponse
	(*GetUnspecifiedRequest)(nil),        // 2: grpcapi.authz.testdata.v1.GetUnspecifiedRequest
	(*GetUnspecifiedResponse)(nil),       // 3: grpcapi.authz.testdata.v1.GetUnspecifiedResponse
	(*GetServerNoScopeRequest)(nil),      // 4: grpcapi.authz.testdata.v1.GetServerNoScopeRequest
	(*GetServerNoScopeResponse)(nil),     // 5: grpcapi.authz.testdata.v1.GetServerNoScopeResponse
	(*GetPermissionNoPermsRequest)(nil),  // 6: grpcapi.authz.testdata.v1.GetPermissionNoPermsRequest
	(*GetPermissionNoPermsResponse)(nil), // 7: grpcapi.authz.testdata.v1.GetPermissionNoPermsResponse
	(*GetSystemRequest)(nil),             // 8: grpcapi.authz.testdata.v1.GetSystemRequest
	(*GetSystemResponse)(nil),            // 9: grpcapi.authz.testdata.v1.GetSystemResponse
	(*GetAlienScopeRequest)(nil),         // 10: grpcapi.authz.testdata.v1.GetAlienScopeRequest
	(*GetAlienScopeResponse)(nil),        // 11: grpcapi.authz.testdata.v1.GetAlienScopeResponse
	(*GetOplessScopeRequest)(nil),        // 12: grpcapi.authz.testdata.v1.GetOplessScopeRequest
	(*GetOplessScopeResponse)(nil),       // 13: grpcapi.authz.testdata.v1.GetOplessScopeResponse
}
var file_violations_proto_depIdxs = []int32{
	0,  // 0: grpcapi.authz.testdata.v1.BadMissingPolicyService.GetMissingPolicy:input_type -> grpcapi.authz.testdata.v1.GetMissingPolicyRequest
	2,  // 1: grpcapi.authz.testdata.v1.BadUnspecifiedService.GetUnspecified:input_type -> grpcapi.authz.testdata.v1.GetUnspecifiedRequest
	4,  // 2: grpcapi.authz.testdata.v1.BadServerNoScopeService.GetServerNoScope:input_type -> grpcapi.authz.testdata.v1.GetServerNoScopeRequest
	6,  // 3: grpcapi.authz.testdata.v1.BadPermissionNoPermsService.GetPermissionNoPerms:input_type -> grpcapi.authz.testdata.v1.GetPermissionNoPermsRequest
	8,  // 4: grpcapi.authz.testdata.v1.BadSystemService.GetSystem:input_type -> grpcapi.authz.testdata.v1.GetSystemRequest
	10, // 5: grpcapi.authz.testdata.v1.BadAlienScopeService.GetAlienScope:input_type -> grpcapi.authz.testdata.v1.GetAlienScopeRequest
	12, // 6: grpcapi.authz.testdata.v1.BadOplessScopeService.GetOplessScope:input_type -> grpcapi.authz.testdata.v1.GetOplessScopeRequest
	1,  // 7: grpcapi.authz.testdata.v1.BadMissingPolicyService.GetMissingPolicy:output_type -> grpcapi.authz.testdata.v1.GetMissingPolicyResponse
	3,  // 8: grpcapi.authz.testdata.v1.BadUnspecifiedService.GetUnspecified:output_type -> grpcapi.authz.testdata.v1.GetUnspecifiedResponse
	5,  // 9: grpcapi.authz.testdata.v1.BadServerNoScopeService.GetServerNoScope:output_type -> grpcapi.authz.testdata.v1.GetServerNoScopeResponse
	7,  // 10: grpcapi.authz.testdata.v1.BadPermissionNoPermsService.GetPermissionNoPerms:output_type -> grpcapi.authz.testdata.v1.GetPermissionNoPermsResponse
	9,  // 11: grpcapi.authz.testdata.v1.BadSystemService.GetSystem:output_type -> grpcapi.authz.testdata.v1.GetSystemResponse
	11, // 12: grpcapi.authz.testdata.v1.BadAlienScopeService.GetAlienScope:output_type -> grpcapi.authz.testdata.v1.GetAlienScopeResponse
	13, // 13: grpcapi.authz.testdata.v1.BadOplessScopeService.GetOplessScope:output_type -> grpcapi.authz.testdata.v1.GetOplessScopeResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_violations_proto_init() }
func file_violations_proto_init() {
	if File_violations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_violations_proto_rawDesc), len(file_violations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   7,
		},
		GoTypes:           file_violations_proto_goTypes,
		DependencyIndexes: file_violations_proto_depIdxs,
		MessageInfos:      file_violations_proto_msgTypes,
	}.Build()
	File_violations_proto = out.File
	file_violations_proto_goTypes = nil
	file_violations_proto_depIdxs = nil
}
